#configuration
spring.jpa.hibernate.ddl-auto=none
spring.datasource.url=jdbc:mysql://localhost:3306/punkcreate
spring.datasource.username=root
spring.datasource.password=R4h4-ch4n_o@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
jwt.secret=6d526234bd3449ae873b73102c74de68
jwt.lifetime=3600000
file.upload-dir=./upload-dir
#spring.jpa.show-sql=true
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
